@baseURL = http://localhost:3000
@id_do_usuario = 3

### Listar todos os usuários
GET {{baseURL}}/users
Accept: application/json

### Criar um novo usuário
POST {{baseURL}}/users
Content-Type: application/json

{
"name": "Novo Usuario",
"email": "novo_usuario@example.com",
"phone_number": "11999999988"
}

### Criar usuário com email inválido (erro esperado)
POST {{baseURL}}/users
Content-Type: application/json

{
"name": "Teste Email Invalido",
"email": "email_invalido",
"phone_number": "11999999999"
}

### Criar usuário com email repetido (erro esperado)
POST {{baseURL}}/users
Content-Type: application/json

{
"name": "Marcos Silva",
"email": "novo_usuario@example.com",
"phone_number": "11999999999"
}

### Atualizar um usuário existente (substitua @id_do_usuario)
PUT {{baseURL}}/users/{{id_do_usuario}}
Content-Type: application/json

{
"name": "Marcos Silva Atualizado",
"email": "marcosatualizado2@example.com",
"phone_number": "11977777"
}

### Atualizar usuário inexistente (erro esperado)
PUT {{baseURL}}/users/9999
Content-Type: application/json

{
"name": "Usuario Inexistente",
"email": "inexistente@example.com",
"phone_number": "11977777777"
}

### Deletar um usuário existente (substitua @id_do_usuario)
DELETE {{baseURL}}/users/{{id_do_usuario}}
Accept: application/json

### Deletar um usuário inexistente (erro esperado)
DELETE {{baseURL}}/users/9999
Accept: application/json
